spring:
  application:
    name: my-zipkin
  main:
    allow-bean-definition-overriding: true
server:
  port: 8097
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    web:
      server:
        auto-time-requests: false
        request:
          autotime:
            enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/