spring:
  application:
    name: my-zuul
server:
  port: 8094
zuul:
  routes:
    # 以 /api/r 开头的请求都转发给my-ribbon
    api-ribbon:
      path: /api/r/**
      serviceId: my-ribbon
    # 以 /api/f 开头的请求都转发给my-feign
    api-feign:
      path: /api/f/**
      serviceId: my-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/