server:
  port: 8092
spring:
  application:
    name: my-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /