server:
  port: 8088
spring:
  application:
    name: my-register-server
eureka:
  client:
    register-with-eureka: false #表示不注册，做集群是设置成true
    fetch-registry: false #表示不拉取，做集群是设置成true
  instance:
    prefer-ip-address: true