server:
  port: 8101
spring:
  application:
    name: my-consul-client
  boot:
    admin:
      client:
        url: http://localhost:8099
  zipkin:
    # 基于Undertow WEB服务器，提供对外端口：9411，Tomcat:8080
    base-url: http://localhost:9411
  cloud:
    consul:
      host: localhost
      port: 8500
# 打开断路器，否则仪表盘监测不到数据
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      # actuator的前缀地址
      base-path: /
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always