server:
  port: 8099
spring:
  application:
    name: spring-cloud-feign
  zipkin:
    # 基于Undertow WEB服务器，提供对外端口：9411，Tomcat:8080
    base-url: http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/