server:
  port: 8090
spring:
  application:
    name: my-eureka-client #注册在注册中心的名字，它会进行键值对映射url
  zipkin:
    # 基于Undertow WEB服务器，提供对外端口：9411，Tomcat:8080
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/ #注册到注册中心
  instance:
    prefer-ip-address: true #用两种方式进行注册，一种是使用主机名注册，一种是使用ip地址进行注册，这里使用ip地址进行注册