server:
  port: 8100
spring:
  application:
    name: my-consul-server
  boot:
    admin:
      client:
        url: http://localhost:8099
  zipkin:
    # 基于Undertow WEB服务器，提供对外端口：9411，Tomcat:8080
    base-url: http://localhost:9411
  cloud:
    consul:
      host: localhost
      port: 8500
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always